import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh' | 'ko' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.courses': 'Our Courses',
    'nav.team': 'Our Team',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.premier': 'Premier Training Academy',
    'hero.title': 'Valentia Cabin Crew Academy',
    'hero.subtitle': 'Elevating Aviation Excellence',
    'hero.description': 'Transform your passion for aviation into a prestigious career with our world-class cabin crew training programs in Malaysia. Welcoming international students from Japan, Korea, and Southeast Asian countries.',
    'hero.cta': 'Explore Courses',
    'hero.iata.title': 'IATA Certified',
    'hero.iata.subtitle': 'International Standards',
    'hero.expert.title': 'Expert Instructors',
    'hero.expert.subtitle': 'Industry Professionals',
    
    // Hero Stats
    'hero.stats.graduates': 'Graduates',
    'hero.stats.crewPlacement': 'Crew Placement',
    'hero.stats.studentRating': 'Student Rating',
    
    // About Us
    'about.title': 'About Valentia Cabin Crew Academy',
    'about.subtitle': 'Your Gateway to Aviation Excellence',
    'about.description1': 'Established as Malaysia\'s premier cabin crew training institution, Valentia Cabin Crew Academy is dedicated to nurturing the next generation of aviation professionals. Our state-of-the-art facilities and experienced instructors provide comprehensive training that meets international aviation standards.',
    'about.description2': 'We pride ourselves on delivering world-class education that combines theoretical knowledge with practical hands-on experience. Our graduates are equipped with the skills, confidence, and professionalism required to excel in the dynamic aviation industry.',
    'about.mission': 'Our Mission',
    'about.missionText': 'To provide exceptional cabin crew training that exceeds industry standards and prepares our students for successful careers in aviation.',
    'about.vision': 'Our Vision',
    'about.visionText': 'To be recognized as the leading cabin crew training academy in Southeast Asia, known for excellence and innovation.',
    
    // Courses
    'courses.title': 'Training Courses',
    'courses.subtitle': 'Comprehensive Programs for Aviation Excellence',
    'courses.features': 'Course Features',
    'courses.courseFee': 'Course Fee',
    'courses.priceNote': '*Prices may vary for international students',
    'courses.learnMoreAndApply': 'Learn More & Apply',
    'courses.advanced.title': 'Advanced Cabin Crew Diploma',
    'courses.advanced.duration': '1 Year Programme',
    'courses.advanced.description': 'Advanced training including leadership skills, crew resource management, international protocols, and specialized aircraft systems. This comprehensive program combines IATA certification with Harvard Management modules for complete professional development.',
    'courses.english.title': 'English Language Proficiency',
    'courses.english.duration': '6 Months Programme',
    'courses.english.description': 'Specialized English language training for aviation professionals, focusing on aviation terminology, communication skills, and international standards. Designed to achieve ICAO Level 4+ certification.',
    'courses.basic.title': 'Basic Cabin Crew Training',
    'courses.basic.duration': '6 Months Programme',
    'courses.basic.description': 'Comprehensive foundation training covering essential safety procedures, customer service fundamentals, aviation regulations, and professional development for beginners. Perfect starting point for aviation career with hands-on practice.',
    
    // Course Features
    'features.iata': 'IATA Certification',
    'features.harvard': 'Harvard Management Modules',
    'features.jobplacement': 'Crew Placement Support',
    'features.airlines': 'International Airlines Network',
    'features.practical': 'Practical Training',
    'features.leadership': 'Leadership Skills',
    'features.icao': 'ICAO Level 4+ Certification',
    'features.interviews': 'Mock Interviews',
    'features.pronunciation': 'Pronunciation Training',
    'features.vocabulary': 'Industry Vocabulary',
    'features.speaking': 'Public Speaking Skills',
    'features.basic': 'Basic Certification',
    'features.foundation': 'Foundation Skills',
    'features.introduction': 'Industry Introduction',
    'features.guidance': 'Career Guidance',
    'features.support': '24/7 Support',
    
    // Course Detail Page
    'courseDetail.overview': 'Overview',
    'courseDetail.programmeModules': 'Programme Modules',
    'courseDetail.iataModules': 'IATA Modules',
    'courseDetail.communicationSkills': 'Communication Skills',
    'courseDetail.styleAndImage': 'Style and Image',
    'courseDetail.aircraftSafety': 'Aircraft Safety',
    'courseDetail.harvardModules': 'Harvard Management Modules',
    'courseDetail.basicModules': 'Basic Training Modules',
    'courseDetail.harvardDescription': 'To claim your Leadership & Management Diploma, you must successfully complete both the eligible IATA course and 10 HMM© modules.',
    'courseDetail.entryRequirements': 'Entry Requirements',
    'courseDetail.academicRequirements': 'Academic Requirements',
    'courseDetail.physicalRequirements': 'Physical Requirements',
    'courseDetail.careerOpportunities': 'Career Opportunities',
    'courseDetail.perks': 'Perks of being part of a cabin crew',
    'courseDetail.quickInfo': 'Quick Information',
    'courseDetail.contactInfo': 'Contact Information',
    'courseDetail.readyToStart': 'Ready to Start Your Journey?',
    'courseDetail.joinNextIntake': 'Join our next intake and begin your aviation career today.',
    'courseDetail.applyNow': 'Apply Now',
    'courseDetail.backToCourses': 'Back to Courses',
    'courseDetail.courseNotFound': 'Course Not Found',
    'courseDetail.iataCertified': 'IATA Certified Programme',
    'courseDetail.duration': 'Duration',
    'courseDetail.study': 'Study',
    'courseDetail.intake': 'Intake',
    'courseDetail.studyWeek': '3 days per week',
    'courseDetail.intakeMonths': 'January, April, June, August, December',
    'courseDetail.basedOnAirline': '*Based on the airline',
    
    // Course Content - Advanced
    'courses.advanced.subtitle': 'Leadership & Management Programme',
    'courses.advanced.overview': 'A world-class leadership and management diploma.\n\nThis training program combines IATA\'s trusted Airline Customer Service Course or Airline Cabin Crew Course with Harvard ManageMentor (HMM)©, a state-of-the-art media-rich training platform furnished by Harvard Business Faculty, global business leaders and practitioners in the field of leadership development.',
    'courses.advanced.modules.iata.1': 'The Airline Industry Today',
    'courses.advanced.modules.iata.2': 'Better Standard of Customer Service',
    'courses.advanced.modules.iata.3': 'New Trends in Customer Service',
    'courses.advanced.modules.iata.4': 'Customer Perception',
    'courses.advanced.modules.iata.5': 'Customer Contact Techniques',
    'courses.advanced.modules.iata.6': 'Social Styles and Tact',
    'courses.advanced.modules.iata.7': 'Dealing with Complaints',
    'courses.advanced.modules.iata.8': 'Managing Stress and Pressure',
    'courses.advanced.modules.communication.1': 'English Communication',
    'courses.advanced.modules.communication.2': 'Public Speaking',
    'courses.advanced.modules.communication.3': 'Presentation Skills',
    'courses.advanced.modules.style.1': 'Etiquette and Deportment',
    'courses.advanced.modules.style.2': 'Skin Care and Hygiene',
    'courses.advanced.modules.style.3': 'Professional Make-up and Hair Makeover',
    'courses.advanced.modules.style.4': 'Cabin Crew Healthy Living/Lifestyles',
    
    // Aircraft Safety Modules
    'courses.advanced.modules.safety.1': 'Aircraft Emergency Procedures',
    'courses.advanced.modules.safety.2': 'Fire Safety and Prevention',
    'courses.advanced.modules.safety.3': 'Evacuation Protocols',
    'courses.advanced.modules.safety.4': 'Medical Emergency Response',
    'courses.advanced.modules.safety.5': 'Security Awareness Training',
    'courses.advanced.modules.safety.6': 'Weather-Related Safety',
    
    'courses.advanced.modules.harvard.1': 'Coaching',
    'courses.advanced.modules.harvard.2': 'Customer Focus',
    'courses.advanced.modules.harvard.3': 'Decision Making',
    'courses.advanced.modules.harvard.4': 'Ethics at Work',
    'courses.advanced.modules.harvard.5': 'Goal Setting',
    'courses.advanced.modules.harvard.6': 'Innovation and Creativity',
    'courses.advanced.modules.harvard.7': 'Leading People',
    'courses.advanced.modules.harvard.8': 'Strategic Thinking',
    'courses.advanced.modules.harvard.9': 'Stress Management',
    'courses.advanced.modules.harvard.10': 'Time Management',
    
    // Course Content - English
    'courses.english.subtitle': 'ICAO Level 4+ Certification Programme',
    'courses.english.overview': 'Elevate your career aspirations with the IATA Airline Customer Service course, designed to prepare you for the dynamic world of aviation. This program equips you with the essential knowledge, skills, and attitude to provide outstanding customer service and create memorable passenger experiences.',
    
    // Course Content - Basic
    'courses.basic.subtitle': 'Foundation Programme',
    'courses.basic.overview': 'Perfect starting point for your aviation career. This foundation program covers essential safety procedures, customer service fundamentals, and aviation regulations for beginners.',
    'courses.basic.modules.basic.1': 'Basic Safety Procedures',
    'courses.basic.modules.basic.2': 'Customer Service Fundamentals',
    'courses.basic.modules.basic.3': 'Aviation Regulations',
    'courses.basic.modules.basic.4': 'Health & Hygiene',
    'courses.basic.modules.basic.5': 'Teamwork Skills',
    'courses.basic.modules.basic.6': 'Professional Grooming',
    'courses.basic.modules.basic.7': 'Emergency Procedures',
    'courses.basic.modules.basic.8': 'Communication Basics',
    
    // Entry Requirements
    'requirements.academic.1': 'High school graduation certificate',
    'requirements.academic.2': 'Trial Examination/Forecast Results',
    'requirements.physical.1': '157 cm (female)',
    'requirements.physical.2': '165cm (male)',
    
    // Career Opportunities
    'career.1': 'International Airlines Worldwide',
    'career.2': 'Flight Operations',
    'career.3': 'Cadet Pilots',
    'career.4': 'Private Jets',
    'career.5': 'Airports Worldwide',
    'career.6': 'Hospitality Professionals',
    'career.7': 'Tourism Professionals',
    'career.8': 'Public Relations Experts',
    'career.9': 'Customer Service Executives',
    'career.10': 'Aviation Professional Trainers',
    'career.11': 'Performance Management',
    'career.12': 'Airline Management',
    'career.13': 'Recruitment Specialists',
    
    // Perks
    'perks.1': 'Salary – RM6000 to RM12000*',
    'perks.2': 'Tax-free employment package',
    'perks.3': 'International medical coverage and life insurance',
    'perks.4': 'Exclusive travel benefits for self and immediate family*',
    'perks.5': 'Discounted tickets',
    'perks.6': 'Welcome bonus of up to 550 USD*',
    'perks.7': 'Annual bonus*',
    'perks.8': 'Competitive End of Service benefits',
    'perks.9': 'Fast track promotions and excellent career opportunities',
    'perks.10': 'Fully furnished accommodation and free utilities*',
    'perks.11': 'Free transportation to work and back*',
    'perks.12': 'Annual leave of up to 30 days per year*',
    'perks.13': 'Luxury layover hotels',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Start Your Aviation Journey Today',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Operating Hours',
    'contact.hours.weekdays': 'Mon - Fri: 9:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Sat: 9:00 AM - 2:00 PM',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Submitting...',
    'contact.form.success': 'Message sent successfully! We\'ll get back to you within 24 hours.',
    'contact.form.error': 'Failed to send message. Please try again later.',
    'contact.form.name.placeholder': 'Your full name',
    'contact.form.email.placeholder': 'your.email@example.com',
    'contact.form.phone.placeholder': '+60 12 345 6789',
    'contact.form.message.placeholder': 'Tell us about your interest in our cabin crew training programs...',
    'contact.form.course.label': 'Interested Course',
    'contact.form.course.placeholder': 'Select a course',
    'contact.form.course.advanced': 'Advanced Cabin Crew Diploma (1 Year)',
    'contact.form.course.english': 'English Language Proficiency (6 Months)',
    'contact.form.course.basic': 'Basic Cabin Crew Training (6 Months)',
    'contact.form.attachments': 'Attachments',
    'contact.form.attachments.optional': 'Optional',
    'contact.form.attachments.hint': 'Upload graduation certificates, ID cards, etc. Supported formats: PDF, JPG, PNG, DOC, DOCX',
    'contact.form.attachments.uploaded': 'Uploaded Files',
    'contact.form.attachments.remove': 'Remove',

    // Validation
    'validation.emailDotCom': 'Email must end with .com',
    'validation.messageRequired': 'Message is required',
    
    // Contact Section Headers
    'contact.getInTouch': 'Get In Touch',
    'contact.contactInformation': 'Contact Information',
    
      // Header
  'header.contactUs': 'Contact Us',
  'header.selectLanguage': 'Select Language',
  
  // Team Members
  'team.title': 'Our Team Members',
  'team.subtitle': 'Meet the passionate professionals behind Valentia Cabin Crew Academy. Our experienced team is dedicated to shaping the future of aviation professionals.',
      'team.ceo.title': 'Founder',
  'team.ceo.description': 'Visionary leader with extensive experience in aviation training and business development. Committed to excellence and innovation in cabin crew education.',
  'team.ceo.experience': '15+ years in aviation industry',
  'team.ceo.expertise': 'Strategic leadership, Business development, Aviation regulations',
  'team.instructor1.title': 'Aviation Training Specialist',
  'team.instructor1.description': 'Experienced cabin crew professional with international airline experience. Specializes in safety procedures and customer service excellence.',
  'team.instructor1.experience': '12+ years as cabin crew',
  'team.instructor1.expertise': 'Safety procedures, Customer service, Emergency protocols',
  'team.instructor2.title': 'English Language Specialist',
  'team.instructor2.description': 'Certified English language instructor with expertise in aviation terminology and ICAO standards. Specializes in helping students achieve ICAO Level 4+ certification.',
  'team.instructor2.experience': '10+ years in English language training',
  'team.instructor2.expertise': 'Aviation English, ICAO standards, Pronunciation training, Communication skills',
  'team.experience': 'Experience',
  'team.expertise': 'Areas of Expertise',
  'team.contact': 'Contact',
  'team.cta.title': 'Ready to Start Your Aviation Journey?',
  'team.cta.description': 'Join our team of professionals and take the first step towards your cabin crew career. Contact us today to learn more about our training programs.',
  'team.cta.button': 'Get Started',
  
  // Course Levels
    'courseLevel.advanced': 'Advanced',
    'courseLevel.englishPlus': 'English Plus',
    'courseLevel.beginner': 'Beginner',
    
    // Course Duration
    'courseDuration.1Year': '1 Year',
    'courseDuration.6Months': '6 Months',
    
    // About Features
    'about.features.iata.title': 'IATA Certified Programs',
    'about.features.iata.description': 'All our courses meet international aviation training standards.',
    'about.features.expert.title': 'Expert Instructors',
    'about.features.expert.description': 'Learn from industry professionals with decades of experience.',
    'about.features.global.title': 'Global Recognition',
    'about.features.global.description': 'Our certification is recognized by airlines worldwide.',
    'about.features.curriculum.title': 'Comprehensive Curriculum',
    'about.features.curriculum.description': 'Complete training covering all aspects of cabin crew duties.',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.description': 'Malaysia\'s premier cabin crew training academy, dedicated to excellence in aviation education and professional development.',
    'footer.quickLinks': 'Quick Links',
    'footer.ourCourses': 'Our Courses',
    'footer.contactInfo': 'Contact Info',
    'footer.admissions': 'Admissions',
    'footer.advancedTraining': 'Advanced Cabin Crew Training',
    'footer.basicTraining': 'Basic Cabin Crew Training',
    'footer.englishProficiency': 'English Language Proficiency',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.courses': '我们的课程',
    'nav.team': '我们的团队',
    'nav.contact': '联系我们',
    
    // Hero Section
    'hero.premier': '顶级培训学院',
    'hero.title': 'Valentia 空乘学院',
    'hero.subtitle': '提升航空卓越',
    'hero.description': '通过我们在马来西亚的世界级空乘培训课程，将您对航空的热情转化为崇高的职业。欢迎来自日本、韩国和东南亚各国的国际学生。',
    'hero.cta': '探索课程',
    'hero.iata.title': 'IATA 认证',
    'hero.iata.subtitle': '国际标准',
    'hero.expert.title': '专业讲师',
    'hero.expert.subtitle': '行业专家',
    
    // Hero Stats
    'hero.stats.graduates': '毕业生',
    'hero.stats.crewPlacement': '船员安置',
    'hero.stats.studentRating': '学生评分',
    
    // About Us
    'about.title': '关于 Valentia 空乘学院',
    'about.subtitle': '您通向航空卓越的门户',
    'about.description1': 'Valentia 空乘学院作为马来西亚首屈一指的空乘培训机构，致力于培养下一代航空专业人才。我们最先进的设施和经验丰富的教师提供符合国际航空标准的综合培训。',
    'about.description2': '我们以提供世界级教育为荣，将理论知识与实践经验相结合。我们的毕业生具备在充满活力的航空业中取得成功所需的技能、信心和专业素养。',
    'about.mission': '我们的使命',
    'about.missionText': '提供超越行业标准的卓越空乘培训，为学生在航空领域的成功职业生涯做好准备。',
    'about.vision': '我们的愿景',
    'about.visionText': '成为东南亚领先的空乘培训学院，以卓越和创新著称。',
    
    // About Features
    'about.features.iata.title': 'IATA认证课程',
    'about.features.iata.description': '我们所有课程都符合国际航空培训标准。',
    'about.features.expert.title': '专业讲师',
    'about.features.expert.description': '向拥有数十年经验的行业专业人士学习。',
    'about.features.global.title': '全球认可',
    'about.features.global.description': '我们的认证得到全球航空公司的认可。',
    'about.features.curriculum.title': '综合课程',
    'about.features.curriculum.description': '涵盖空乘职责各个方面的完整培训。',
    

    
    // Courses
    'courses.title': '培训课程',
    'courses.subtitle': '航空卓越的综合课程',
    'courses.features': '课程特色',
    'courses.courseFee': '课程费用',
    'courses.priceNote': '*国际学生价格可能有所不同',
    'courses.learnMoreAndApply': '了解更多并申请',
    'courses.advanced.title': '高级空乘文凭',
    'courses.advanced.duration': '1年课程',
    'courses.advanced.description': '高级培训包括领导技能、机组资源管理、国际协议和专业飞机系统。这个综合课程结合IATA认证和哈佛管理模块，实现完整的专业发展。',
    'courses.english.title': '英语语言能力',
    'courses.english.duration': '6个月课程',
    'courses.english.description': '专为航空专业人士设计的英语语言培训，重点关注航空术语、沟通技巧和国际标准。旨在达到ICAO 4+级认证。',
    'courses.basic.title': '基础空乘培训',
    'courses.basic.duration': '6个月课程',
    'courses.basic.description': '全面的基础培训涵盖基本安全程序、客户服务基础、航空法规和初学者专业发展。航空职业的完美起点，提供实践训练。',
    
    // Course Features
    'features.iata': 'IATA认证',
    'features.harvard': '哈佛管理模块',
    'features.jobplacement': '机组就职支持',
    'features.airlines': '国际航空公司网络',
    'features.practical': '实践培训',
    'features.leadership': '领导技能',
    'features.icao': 'ICAO 4+级认证',
    'features.interviews': '模拟面试',
    'features.pronunciation': '发音训练',
    'features.vocabulary': '行业词汇',
    'features.speaking': '公众演讲技能',
    'features.basic': '基础认证',
    'features.foundation': '基础技能',
    'features.introduction': '行业介绍',
    'features.guidance': '职业指导',
    'features.support': '24/7支持',
    
    // Course Detail Page
    'courseDetail.overview': '概述',
    'courseDetail.programmeModules': '课程模块',
    'courseDetail.iataModules': 'IATA模块',
    'courseDetail.communicationSkills': '沟通技能',
    'courseDetail.styleAndImage': '形象与风格',
    'courseDetail.aircraftSafety': '空中飞机安全',
    'courseDetail.harvardModules': '哈佛管理模块',
    'courseDetail.basicModules': '基础训练模块',
    'courseDetail.harvardDescription': '要获得领导力与管理文凭，您必须成功完成合格的IATA课程和10个HMM©模块。',
    'courseDetail.entryRequirements': '入学要求',
    'courseDetail.academicRequirements': '学术要求',
    'courseDetail.physicalRequirements': '身体要求',
    'courseDetail.careerOpportunities': '职业机会',
    'courseDetail.perks': '空乘人员的福利',
    'courseDetail.quickInfo': '快速信息',
    'courseDetail.contactInfo': '联系信息',
    'courseDetail.readyToStart': '准备开始您的旅程？',
    'courseDetail.joinNextIntake': '加入我们的下一期招生，今天就开始您的航空职业生涯。',
    'courseDetail.applyNow': '立即申请',
    'courseDetail.backToCourses': '返回课程',
    'courseDetail.courseNotFound': '课程未找到',
    'courseDetail.iataCertified': 'IATA认证课程',
    'courseDetail.duration': '课程时长',
    'courseDetail.study': '学习',
    'courseDetail.intake': '招生',
    'courseDetail.studyWeek': '每周3天',
    'courseDetail.intakeMonths': '一月、四月、六月、八月、十二月',
    'courseDetail.basedOnAirline': '*基于航空公司',
    
    // Course Content - Advanced
    'courses.advanced.subtitle': '领导力与管理课程',
    'courses.advanced.overview': '世界级的领导力与管理文凭。\n\n这个培训课程结合了IATA可信赖的航空公司客户服务课程或航空公司空乘课程与哈佛管理导师(HMM)©，这是一个由哈佛商学院教师、全球商业领袖和领导力发展领域的从业者提供的最先进的媒体丰富培训平台。',
    'courses.advanced.modules.iata.1': '当今航空业',
    'courses.advanced.modules.iata.2': '更好的客户服务标准',
    'courses.advanced.modules.iata.3': '客户服务新趋势',
    'courses.advanced.modules.iata.4': '客户感知',
    'courses.advanced.modules.iata.5': '客户接触技巧',
    'courses.advanced.modules.iata.6': '社交风格与策略',
    'courses.advanced.modules.iata.7': '处理投诉',
    'courses.advanced.modules.iata.8': '管理压力',
    'courses.advanced.modules.communication.1': '英语沟通',
    'courses.advanced.modules.communication.2': '公众演讲',
    'courses.advanced.modules.communication.3': '演讲技巧',
    'courses.advanced.modules.style.1': '礼仪与举止',
    'courses.advanced.modules.style.2': '护肤与卫生',
    'courses.advanced.modules.style.3': '专业化妆与发型改造',
    'courses.advanced.modules.style.4': '空乘健康生活/生活方式',
    
    // 空中飞机安全模块
    'courses.advanced.modules.safety.1': '飞机应急程序',
    'courses.advanced.modules.safety.2': '消防安全与预防',
    'courses.advanced.modules.safety.3': '疏散协议',
    'courses.advanced.modules.safety.4': '医疗应急响应',
    'courses.advanced.modules.safety.5': '安全意识培训',
    'courses.advanced.modules.safety.6': '天气相关安全',
    
    'courses.advanced.modules.harvard.1': '教练',
    'courses.advanced.modules.harvard.2': '客户关注',
    'courses.advanced.modules.harvard.3': '决策制定',
    'courses.advanced.modules.harvard.4': '工作伦理',
    'courses.advanced.modules.harvard.5': '目标设定',
    'courses.advanced.modules.harvard.6': '创新与创造力',
    'courses.advanced.modules.harvard.7': '领导他人',
    'courses.advanced.modules.harvard.8': '战略思维',
    'courses.advanced.modules.harvard.9': '压力管理',
    'courses.advanced.modules.harvard.10': '时间管理',
    
    // Course Content - English
    'courses.english.subtitle': 'ICAO 4+级认证课程',
    'courses.english.overview': '通过IATA航空公司客户服务课程提升您的职业抱负，该课程旨在为您在充满活力的航空世界中做好准备。该课程为您提供提供卓越客户服务和创造难忘乘客体验所需的基本知识、技能和态度。',
    
    // Course Content - Basic
    'courses.basic.subtitle': '基础课程',
    'courses.basic.overview': '航空职业生涯的完美起点。这个基础课程涵盖基本安全程序、客户服务基础和航空法规，适合初学者。',
    'courses.basic.modules.basic.1': '基本安全程序',
    'courses.basic.modules.basic.2': '客户服务基础',
    'courses.basic.modules.basic.3': '航空法规',
    'courses.basic.modules.basic.4': '健康与卫生',
    'courses.basic.modules.basic.5': '团队合作技能',
    'courses.basic.modules.basic.6': '专业仪容',
    'courses.basic.modules.basic.7': '应急程序',
    'courses.basic.modules.basic.8': '沟通基础',
    
    // Entry Requirements
    'requirements.academic.1': '高中毕业证书',
    'requirements.academic.2': '试考/预测成绩',
    'requirements.physical.1': '157厘米（女性）',
    'requirements.physical.2': '165厘米（男性）',
    
    // Career Opportunities
    'career.1': '全球国际航空公司',
    'career.2': '飞行运营',
    'career.3': '学员飞行员',
    'career.4': '私人飞机',
    'career.5': '全球机场',
    'career.6': '酒店专业人士',
    'career.7': '旅游专业人士',
    'career.8': '公共关系专家',
    'career.9': '客户服务主管',
    'career.10': '航空专业培训师',
    'career.11': '绩效管理',
    'career.12': '航空公司管理',
    'career.13': '招聘专家',
    
    // Perks
    'perks.1': '薪资 – 马币6000至12000*',
    'perks.2': '免税就业套餐',
    'perks.3': '国际医疗保险和人寿保险',
    'perks.4': '本人及直系亲属专属旅行福利*',
    'perks.5': '折扣机票',
    'perks.6': '欢迎奖金高达550美元*',
    'perks.7': '年度奖金*',
    'perks.8': '有竞争力的服务结束福利',
    'perks.9': '快速晋升和优秀职业机会',
    'perks.10': '全装修住宿和免费水电*',
    'perks.11': '免费上下班交通*',
    'perks.12': '每年最多30天年假*',
    'perks.13': '豪华过夜酒店',
    
    // Contact
    'contact.title': '联系我们',
    'contact.subtitle': '今天开始您的航空之旅',
    'contact.address': '地址',
    'contact.phone': '电话',
    'contact.email': '电子邮件',
    'contact.hours': '营业时间',
    'contact.hours.weekdays': '周一至周五：上午9:00 - 下午6:00',
    'contact.hours.saturday': '周六：上午9:00 - 下午2:00',
    'contact.form.title': '给我们留言',
    'contact.form.name': '全名',
    'contact.form.email': '电子邮件地址',
    'contact.form.phone': '电话号码',
    'contact.form.message': '信息',
    'contact.form.submit': '发送消息',
    'contact.form.submitting': '提交中...',
    'contact.form.success': '消息发送成功！我们将在24小时内回复您。',
    'contact.form.error': '发送失败，请稍后重试。',
    'contact.form.name.placeholder': '您的全名',
    'contact.form.email.placeholder': 'your.email@example.com',
    'contact.form.phone.placeholder': '+60 12 345 6789',
    'contact.form.message.placeholder': '请告诉我们您对我们空乘培训项目的兴趣...',
    'contact.form.course.label': '感兴趣的课程',
    'contact.form.course.placeholder': '选择课程',
    'contact.form.course.advanced': '高级空乘文凭 (1年)',
    'contact.form.course.english': '英语语言能力提升 (6个月)',
    'contact.form.course.basic': '基础空乘培训 (6个月)',
    'contact.form.attachments': '附件',
    'contact.form.attachments.optional': '可选',
    'contact.form.attachments.hint': '上传毕业证书、身份证等。支持格式：PDF、JPG、PNG、DOC、DOCX',
    'contact.form.attachments.uploaded': '已上传文件',
    'contact.form.attachments.remove': '删除',

    // Validation
    'validation.emailDotCom': '邮箱必须以 .com 结尾',
    'validation.messageRequired': '消息内容为必填项',
    
    // Contact Section Headers
    'contact.getInTouch': '联系我们',
    'contact.contactInformation': '联系信息',
    
      // Header
  'header.contactUs': '联系我们',
  'header.selectLanguage': '选择语言',
  
  // Team Members
  'team.title': '我们的团队成员',
  'team.subtitle': '认识瓦伦蒂亚空乘学院背后的专业团队。我们经验丰富的团队致力于塑造未来航空专业人士。',
      'team.ceo.title': '创始人',
  'team.ceo.description': '具有丰富航空培训和业务发展经验的远见卓识的领导者。致力于空乘教育的卓越和创新。',
  'team.ceo.experience': '15年以上航空行业经验',
  'team.ceo.expertise': '战略领导力、业务发展、航空法规',
  'team.instructor1.title': '航空培训专家',
  'team.instructor1.description': '具有国际航空公司经验的资深空乘专业人士。专长于安全程序和卓越客户服务。',
  'team.instructor1.experience': '12年以上空乘经验',
  'team.instructor1.expertise': '安全程序、客户服务、应急协议',
  'team.instructor2.title': '英语语言专家',
  'team.instructor2.description': '认证英语语言讲师，专长于航空术语和ICAO标准。专门帮助学生获得ICAO 4+级认证。',
  'team.instructor2.experience': '10年以上英语语言培训经验',
  'team.instructor2.expertise': '航空英语、ICAO标准、发音训练、沟通技巧',
  'team.experience': '经验',
  'team.expertise': '专业领域',
  'team.contact': '联系',
  'team.cta.title': '准备开始您的航空之旅？',
  'team.cta.description': '加入我们的专业团队，迈出空乘职业的第一步。今天就联系我们，了解更多培训课程信息。',
  'team.cta.button': '立即开始',
  
  // Course Levels
    'courseLevel.advanced': '高级',
    'courseLevel.englishPlus': '英语提升',
    'courseLevel.beginner': '初级',
    
    // Course Duration
    'courseDuration.1Year': '1年',
    'courseDuration.6Months': '6个月',
    
    // Footer
    'footer.rights': '保留所有权利。',
    'footer.description': '马来西亚首屈一指的空乘培训学院，致力于航空教育和专业发展的卓越性。',
    'footer.quickLinks': '快速链接',
    'footer.ourCourses': '我们的课程',
    'footer.contactInfo': '联系信息',
    'footer.admissions': '招生',
    'footer.advancedTraining': '高级空乘培训',
    'footer.basicTraining': '基础空乘培训',
    'footer.englishProficiency': '英语语言能力',
    'footer.privacyPolicy': '隐私政策',
    'footer.termsOfService': '服务条款',
  },
  ko: {
    // Navigation
    'nav.home': '홈',
    'nav.about': '회사소개',
    'nav.courses': '우리의 코스',
    'nav.team': '우리 팀',
    'nav.contact': '문의',
    
    // Hero Section
    'hero.premier': '최고의 교육 아카데미',
    'hero.title': 'Valentia 객실승무원 아카데미',
    'hero.subtitle': '항공 우수성 제고',
    'hero.description': '말레이시아의 세계적 수준의 객실승무원 교육 프로그램으로 항공에 대한 열정을 명망 있는 경력으로 전환하세요. 일본, 한국 및 동남아시아 각국의 국제 학생들을 환영합니다.',
    'hero.cta': '코스 탐색',
    'hero.iata.title': 'IATA 인증',
    'hero.iata.subtitle': '국제 표준',
    'hero.expert.title': '전문 강사',
    'hero.expert.subtitle': '업계 전문가',
    
    // Hero Stats
    'hero.stats.graduates': '졸업생',
    'hero.stats.crewPlacement': '승무원 배치',
    'hero.stats.studentRating': '학생 평가',
    
    // About Us
    'about.title': 'Valentia 객실승무원 아카데미 소개',
    'about.subtitle': '항공 우수성으로 가는 관문',
    'about.description1': '말레이시아 최고의 객실승무원 교육 기관으로 설립된 Valentia 객실승무원 아카데미는 차세대 항공 전문가 양성에 전념하고 있습니다. 최첨단 시설과 경험이 풍부한 강사진이 국제 항공 표준을 충족하는 종합적인 교육을 제공합니다.',
    'about.description2': '우리는 이론적 지식과 실제 실습 경험을 결합한 세계적 수준의 교육을 제공하는 것을 자랑스럽게 생각합니다. 우리 졸업생들은 역동적인 항공 산업에서 탁월한 성과를 내는 데 필요한 기술, 자신감 및 전문성을 갖추고 있습니다.',
    'about.mission': '우리의 사명',
    'about.missionText': '업계 표준을 뛰어넘는 뛰어난 객실승무원 교육을 제공하고 학생들이 항공 분야에서 성공적인 경력을 쌓을 수 있도록 준비시키는 것입니다.',
    'about.vision': '우리의 비전',
    'about.visionText': '우수성과 혁신으로 유명한 동남아시아 최고의 객실승무원 교육 아카데미로 인정받는 것입니다.',
    
    // About Features
    'about.features.iata.title': 'IATA 인증 프로그램',
    'about.features.iata.description': '모든 과정이 국제 항공 교육 표준을 충족합니다.',
    'about.features.expert.title': '전문 강사',
    'about.features.expert.description': '수십 년의 경험을 가진 업계 전문가로부터 배우세요.',
    'about.features.global.title': '글로벌 인정',
    'about.features.global.description': '우리의 인증은 전 세계 항공사에서 인정받습니다.',
    'about.features.curriculum.title': '종합 커리큘럼',
    'about.features.curriculum.description': '객실승무원 업무의 모든 측면을 다루는 완전한 교육.',
    
    // Courses
    'courses.title': '교육 코스',
    'courses.subtitle': '항공 우수성을 위한 종합 프로그램',
    'courses.features': '코스 특징',
    'courses.courseFee': '코스 비용',
    'courses.priceNote': '*국제 학생의 경우 가격이 다를 수 있습니다',
    'courses.learnMoreAndApply': '더 알아보고 신청하기',
    'courses.advanced.title': '고급 객실승무원 디플로마',
    'courses.advanced.duration': '1년 프로그램',
    'courses.advanced.description': '리더십 기술, 승무원 자원 관리, 국제 프로토콜 및 특수 항공기 시스템을 포함한 고급 교육입니다. 이 종합 프로그램은 IATA 인증과 하버드 관리 모듈을 결합하여 완전한 전문 개발을 제공합니다.',
    'courses.english.title': '영어 능력 향상',
    'courses.english.duration': '6개월 프로그램',
    'courses.english.description': '항공 전문가를 위한 전문 영어 교육으로, 항공 용어, 의사소통 기술 및 국제 표준에 중점을 둡니다. ICAO 레벨 4+ 인증 달성을 목표로 합니다.',
    'courses.basic.title': '기본 객실승무원 교육',
    'courses.basic.duration': '6개월 프로그램',
    'courses.basic.description': '기본 안전 절차, 고객 서비스 기초, 항공 규정 및 초보자를 위한 전문 개발을 포함한 포괄적인 기본 교육입니다. 실습과 함께 항공 경력의 완벽한 시작점입니다.',
    
    // Course Features
    'features.iata': 'IATA 인증',
    'features.harvard': '하버드 관리 모듈',
    'features.jobplacement': '승무원 배치 지원',
    'features.airlines': '국제 항공사 네트워크',
    'features.practical': '실무 교육',
    'features.leadership': '리더십 기술',
    'features.icao': 'ICAO 레벨 4+ 인증',
    'features.interviews': '모의 면접',
    'features.pronunciation': '발음 교육',
    'features.vocabulary': '업계 어휘',
    'features.speaking': '대중 연설 기술',
    'features.basic': '기본 인증',
    'features.foundation': '기초 기술',
    'features.introduction': '업계 소개',
    'features.guidance': '진로 지도',
    'features.support': '24시간 지원',
    
    // Course Detail Page
    'courseDetail.overview': '개요',
    'courseDetail.programmeModules': '프로그램 모듈',
    'courseDetail.iataModules': 'IATA 모듈',
    'courseDetail.communicationSkills': '의사소통 기술',
    'courseDetail.styleAndImage': '스타일 및 이미지',
    'courseDetail.aircraftSafety': '항공기 안전',
    'courseDetail.harvardModules': '하버드 관리 모듈',
    'courseDetail.basicModules': '기본 훈련 모듈',
    'courseDetail.harvardDescription': '리더십 및 관리 디플로마를 취득하려면 자격을 갖춘 IATA 과정과 10개의 HMM© 모듈을 모두 성공적으로 완료해야 합니다.',
    'courseDetail.entryRequirements': '입학 요건',
    'courseDetail.academicRequirements': '학업 요건',
    'courseDetail.physicalRequirements': '신체 요건',
    'courseDetail.careerOpportunities': '경력 기회',
    'courseDetail.perks': '객실승무원의 혜택',
    'courseDetail.quickInfo': '빠른 정보',
    'courseDetail.contactInfo': '연락처 정보',
    'courseDetail.readyToStart': '여정을 시작할 준비가 되셨나요?',
    'courseDetail.joinNextIntake': '다음 입학생과 함께 항공 경력을 오늘부터 시작하세요.',
    'courseDetail.applyNow': '지금 신청',
    'courseDetail.backToCourses': '코스로 돌아가기',
    'courseDetail.courseNotFound': '코스를 찾을 수 없습니다',
    'courseDetail.iataCertified': 'IATA 인증 프로그램',
    'courseDetail.duration': '기간',
    'courseDetail.study': '학습',
    'courseDetail.intake': '입학',
    'courseDetail.studyWeek': '주 3일',
    'courseDetail.intakeMonths': '1월, 4월, 6월, 8월, 12월',
    'courseDetail.basedOnAirline': '*항공사 기준',
    
    // Course Content - Advanced
    'courses.advanced.subtitle': '리더십 및 관리 프로그램',
    'courses.advanced.overview': '세계적 수준의 리더십 및 관리 디플로마.\n\n이 교육 프로그램은 IATA의 신뢰할 수 있는 항공사 고객 서비스 과정 또는 항공사 객실승무원 과정을 하버드 매니지멘터(HMM)©와 결합합니다. 이는 하버드 비즈니스 스쿨 교수진, 글로벌 비즈니스 리더 및 리더십 개발 분야의 실무자들이 제공하는 최첨단 미디어 풍부 교육 플랫폼입니다.',
    'courses.advanced.modules.iata.1': '오늘날의 항공 산업',
    'courses.advanced.modules.iata.2': '더 나은 고객 서비스 표준',
    'courses.advanced.modules.iata.3': '고객 서비스의 새로운 트렌드',
    'courses.advanced.modules.iata.4': '고객 인식',
    'courses.advanced.modules.iata.5': '고객 접촉 기술',
    'courses.advanced.modules.iata.6': '사회적 스타일과 전술',
    'courses.advanced.modules.iata.7': '불만 처리',
    'courses.advanced.modules.iata.8': '스트레스 및 압박 관리',
    'courses.advanced.modules.communication.1': '영어 의사소통',
    'courses.advanced.modules.communication.2': '대중 연설',
    'courses.advanced.modules.communication.3': '프레젠테이션 기술',
    'courses.advanced.modules.style.1': '예의 및 태도',
    'courses.advanced.modules.style.2': '피부 관리 및 위생',
    'courses.advanced.modules.style.3': '전문 메이크업 및 헤어 메이크오버',
    'courses.advanced.modules.style.4': '객실승무원 건강한 생활/라이프스타일',
    
    // 항공기 안전 모듈
    'courses.advanced.modules.safety.1': '항공기 비상 절차',
    'courses.advanced.modules.safety.2': '화재 안전 및 예방',
    'courses.advanced.modules.safety.3': '대피 프로토콜',
    'courses.advanced.modules.safety.4': '의료 비상 대응',
    'courses.advanced.modules.safety.5': '보안 인식 훈련',
    'courses.advanced.modules.safety.6': '날씨 관련 안전',
    
    'courses.advanced.modules.harvard.1': '코칭',
    'courses.advanced.modules.harvard.2': '고객 중심',
    'courses.advanced.modules.harvard.3': '의사결정',
    'courses.advanced.modules.harvard.4': '직장에서의 윤리',
    'courses.advanced.modules.harvard.5': '목표 설정',
    'courses.advanced.modules.harvard.6': '혁신과 창의성',
    'courses.advanced.modules.harvard.7': '사람 리드하기',
    'courses.advanced.modules.harvard.8': '전략적 사고',
    'courses.advanced.modules.harvard.9': '스트레스 관리',
    'courses.advanced.modules.harvard.10': '시간 관리',
    
    // Course Content - English
    'courses.english.subtitle': 'ICAO 레벨 4+ 인증 프로그램',
    'courses.english.overview': 'IATA 항공사 고객 서비스 과정으로 경력 포부를 높이세요. 이 과정은 역동적인 항공 세계에서 성공할 수 있도록 준비하도록 설계되었습니다. 이 프로그램은 뛰어난 고객 서비스를 제공하고 잊을 수 없는 승객 경험을 만드는 데 필요한 필수 지식, 기술 및 태도를 제공합니다.',
    
    // Course Content - Basic
    'courses.basic.subtitle': '기초 프로그램',
    'courses.basic.overview': '항공 경력의 완벽한 시작점. 이 기초 프로그램은 초보자를 위한 필수 안전 절차, 고객 서비스 기초 및 항공 규정을 다룹니다.',
    'courses.basic.modules.basic.1': '기본 안전 절차',
    'courses.basic.modules.basic.2': '고객 서비스 기초',
    'courses.basic.modules.basic.3': '항공 규정',
    'courses.basic.modules.basic.4': '건강 및 위생',
    'courses.basic.modules.basic.5': '팀워크 기술',
    'courses.basic.modules.basic.6': '전문적인 단정함',
    'courses.basic.modules.basic.7': '비상 절차',
    'courses.basic.modules.basic.8': '의사소통 기초',
    
    // Entry Requirements
    'requirements.academic.1': '고등학교 졸업증서',
    'requirements.academic.2': '시험/예측 결과',
    'requirements.physical.1': '157cm (여성)',
    'requirements.physical.2': '165cm (남성)',
    
    // Career Opportunities
    'career.1': '전 세계 국제 항공사',
    'career.2': '항공 운항',
    'career.3': '사관생도 조종사',
    'career.4': '프라이빗 제트',
    'career.5': '전 세계 공항',
    'career.6': '호스피탈리티 전문가',
    'career.7': '관광 전문가',
    'career.8': '홍보 전문가',
    'career.9': '고객 서비스 임원',
    'career.10': '항공 전문 교육자',
    'career.11': '성과 관리',
    'career.12': '항공사 경영',
    'career.13': '채용 전문가',
    
    // Perks
    'perks.1': '급여 – RM6000에서 RM12000*',
    'perks.2': '세금 면제 고용 패키지',
    'perks.3': '국제 의료 보험 및 생명 보험',
    'perks.4': '본인 및 직계 가족 전용 여행 혜택*',
    'perks.5': '할인 항공권',
    'perks.6': '최대 550 USD 환영 보너스*',
    'perks.7': '연간 보너스*',
    'perks.8': '경쟁력 있는 퇴직 혜택',
    'perks.9': '빠른 승진 및 우수한 경력 기회',
    'perks.10': '완비된 숙소 및 무료 공과금*',
    'perks.11': '무료 출퇴근 교통*',
    'perks.12': '연간 최대 30일 유급 휴가*',
    'perks.13': '고급 숙박 호텔',
    
    // Contact
    'contact.title': '문의하기',
    'contact.subtitle': '오늘 항공 여행을 시작하세요',
    'contact.address': '주소',
    'contact.phone': '전화',
    'contact.email': '이메일',
    'contact.hours': '운영 시간',
    'contact.hours.weekdays': '월-금: 오전 9:00 - 오후 6:00',
    'contact.hours.saturday': '토: 오전 9:00 - 오후 2:00',
    'contact.form.title': '메시지 보내기',
    'contact.form.name': '성명',
    'contact.form.email': '이메일 주소',
    'contact.form.phone': '전화번호',
    'contact.form.message': '메시지',
    'contact.form.submit': '메시지 전송',
    'contact.form.submitting': '제출 중...',
    'contact.form.success': '메시지가 성공적으로 전송되었습니다! 24시간 이내에 답변드리겠습니다.',
    'contact.form.error': '메시지 전송에 실패했습니다. 나중에 다시 시도해주세요.',
    'contact.form.name.placeholder': '전체 이름',
    'contact.form.email.placeholder': 'your.email@example.com',
    'contact.form.phone.placeholder': '+60 12 345 6789',
    'contact.form.message.placeholder': '객실승무원 교육 프로그램에 대한 관심을 알려주세요...',
    'contact.form.course.label': '관심 있는 과정',
    'contact.form.course.placeholder': '과정 선택',
    'contact.form.course.advanced': '고급 객실승무원 디플로마 (1년)',
    'contact.form.course.english': '영어 능력 향상 과정 (6개월)',
    'contact.form.course.basic': '기본 객실승무원 교육 (6개월)',
    'contact.form.attachments': '첨부파일',
    'contact.form.attachments.optional': '선택사항',
    'contact.form.attachments.hint': '졸업증서, 신분증 등을 업로드하세요. 지원 형식: PDF, JPG, PNG, DOC, DOCX',
    'contact.form.attachments.uploaded': '업로드된 파일',
    'contact.form.attachments.remove': '제거',

    // Validation
    'validation.emailDotCom': '이메일은 .com으로 끝나야 합니다',
    'validation.messageRequired': '메시지는 필수 항목입니다',
    
    // Contact Section Headers
    'contact.getInTouch': '연락하기',
    'contact.contactInformation': '연락처 정보',
    
    // Header
    'header.contactUs': '문의하기',
    'header.selectLanguage': '언어 선택',
    
    // Team Members
    'team.title': '우리 팀 멤버',
    'team.subtitle': 'Valentia Cabin Crew Academy의 열정적인 전문가들을 만나보세요. 우리의 경험 많은 팀은 항공 전문가의 미래를 형성하는 데 전념하고 있습니다.',
    'team.ceo.title': '창립자',
    'team.ceo.description': '항공 교육 및 비즈니스 개발에 광범위한 경험을 가진 비전 있는 리더. 객실승무원 교육의 우수성과 혁신에 전념.',
    'team.ceo.experience': '항공 산업 15년 이상 경험',
    'team.ceo.expertise': '전략적 리더십, 비즈니스 개발, 항공 규정',
      'team.instructor1.title': '항공 교육 전문가',
  'team.instructor1.description': '국제 항공사 경험이 있는 숙련된 객실승무원 전문가. 안전 절차 및 고객 서비스 우수성 전문.',
  'team.instructor1.experience': '객실승무원 12년 이상 경험',
  'team.instructor1.expertise': '안전 절차, 고객 서비스, 비상 프로토콜',
  'team.instructor2.title': '영어 언어 전문가',
  'team.instructor2.description': '항공 용어 및 ICAO 표준에 전문성을 가진 인증된 영어 언어 강사. 학생들이 ICAO 레벨 4+ 인증을 달성하도록 돕는 전문가.',
  'team.instructor2.experience': '영어 언어 교육 10년 이상 경험',
  'team.instructor2.expertise': '항공 영어, ICAO 표준, 발음 훈련, 의사소통 기술',
    'team.experience': '경험',
    'team.expertise': '전문 분야',
    'team.contact': '연락',
    'team.cta.title': '항공 여정을 시작할 준비가 되셨나요?',
    'team.cta.description': '우리의 전문가 팀에 합류하고 객실승무원 경력을 위한 첫 걸음을 내딛으세요. 오늘 우리에게 연락하여 교육 과정에 대해 더 알아보세요.',
    'team.cta.button': '시작하기',
    
    // Course Levels
    'courseLevel.advanced': '고급',
    'courseLevel.englishPlus': '영어 플러스',
    'courseLevel.beginner': '초급',
    
    // Course Duration
    'courseDuration.1Year': '1년',
    'courseDuration.6Months': '6개월',
    
    // Footer
    'footer.rights': '모든 권리 보유.',
    'footer.description': '말레이시아 최고의 객실승무원 교육 아카데미로, 항공 교육 및 전문 개발의 우수성에 전념합니다.',
    'footer.quickLinks': '빠른 링크',
    'footer.ourCourses': '우리의 코스',
    'footer.contactInfo': '연락처 정보',
    'footer.admissions': '입학',
    'footer.advancedTraining': '고급 객실승무원 교육',
    'footer.basicTraining': '기본 객실승무원 교육',
    'footer.englishProficiency': '영어 능력 향상',
    'footer.privacyPolicy': '개인정보 보호정책',
    'footer.termsOfService': '서비스 약관',
  },
  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.courses': '私たちのコース',
    'nav.team': '私たちのチーム',
    'nav.contact': 'お問い合わせ',
    
    // Hero Section
    'hero.premier': '最高の訓練アカデミー',
    'hero.title': 'Valentia キャビンクルー アカデミー',
    'hero.subtitle': '航空の卓越性を高める',
    'hero.description': 'マレーシアの世界クラスのキャビンクルー訓練プログラムで、航空への情熱を名誉あるキャリアに変えましょう。日本、韓国、東南アジア各国からの国際学生を歓迎します。',
    'hero.cta': 'コースを探索',
    'hero.iata.title': 'IATA認定',
    'hero.iata.subtitle': '国際基準',
    'hero.expert.title': '専門講師',
    'hero.expert.subtitle': '業界専門家',
    
    // Hero Stats
    'hero.stats.graduates': '卒業生',
    'hero.stats.crewPlacement': '乗務員配置',
    'hero.stats.studentRating': '学生評価',
    
    // About Us
    'about.title': 'Valentia キャビンクルー アカデミーについて',
    'about.subtitle': '航空の卓越性への入り口',
    'about.description1': 'マレーシア最高のキャビンクルー訓練機関として設立されたValentia キャビンクルー アカデミーは、次世代の航空専門家の育成に専念しています。最先端の設備と経験豊富な講師陣が、国際航空基準を満たす包括的な訓練を提供します。',
    'about.description2': '理論的知識と実践的な経験を組み合わせた世界クラスの教育を提供することを誇りに思っています。卒業生は、ダイナミックな航空業界で優れた成果を上げるために必要なスキル、自信、プロフェッショナリズムを身に付けています。',
    'about.mission': '私たちの使命',
    'about.missionText': '業界標準を超える優れたキャビンクルー訓練を提供し、学生が航空分野で成功するキャリアを築けるよう準備することです。',
    'about.vision': '私たちのビジョン',
    'about.visionText': '卓越性と革新で知られる東南アジア有数のキャビンクルー訓練アカデミーとして認識されることです。',
    
    // About Features
    'about.features.iata.title': 'IATA認定プログラム',
    'about.features.iata.description': 'すべてのコースが国際航空訓練基準を満たしています。',
    'about.features.expert.title': '専門講師',
    'about.features.expert.description': '数十年の経験を持つ業界専門家から学びましょう。',
    'about.features.global.title': 'グローバル認定',
    'about.features.global.description': '私たちの認定は世界中の航空会社で認められています。',
    'about.features.curriculum.title': '包括的カリキュラム',
    'about.features.curriculum.description': 'キャビンクルーの職務のすべての側面をカバーする完全な訓練。',
    
    // Courses
    'courses.title': '訓練コース',
    'courses.subtitle': '航空の卓越性のための包括的プログラム',
    'courses.features': 'コース特徴',
    'courses.courseFee': 'コース料金',
    'courses.priceNote': '*国際学生の場合、料金が異なる場合があります',
    'courses.learnMoreAndApply': '詳細を見て申し込む',
    'courses.advanced.title': '上級キャビンクルー ディプロマ',
    'courses.advanced.duration': '1年間プログラム',
    'courses.advanced.description': 'リーダーシップスキル、乗務員リソース管理、国際プロトコル、特殊航空機システムを含む上級訓練です。この包括的プログラムはIATA認証とハーバード管理モジュールを組み合わせて、完全な専門開発を提供します。',
    'courses.english.title': '英語能力向上',
    'courses.english.duration': '6ヶ月プログラム',
    'courses.english.description': '航空専門家のための専門英語訓練で、航空用語、コミュニケーションスキル、国際基準に焦点を当てています。ICAOレベル4+認証の取得を目指します。',
    'courses.basic.title': '基本キャビンクルー訓練',
    'courses.basic.duration': '6ヶ月プログラム',
    'courses.basic.description': '基本安全手順、顧客サービス基礎、航空規則、初級者向け専門開発を含む包括的な基本訓練です。実践訓練付きで航空キャリアの完璧なスタート地点です。',
    
    // Course Features
    'features.iata': 'IATA認証',
    'features.harvard': 'ハーバード管理モジュール',
    'features.jobplacement': '乗務員配置支援',
    'features.airlines': '国際航空会社ネットワーク',
    'features.practical': '実践訓練',
    'features.leadership': 'リーダーシップスキル',
    'features.icao': 'ICAOレベル4+認証',
    'features.interviews': '模擬面接',
    'features.pronunciation': '発音訓練',
    'features.vocabulary': '業界用語',
    'features.speaking': '公衆演説スキル',
    'features.basic': '基本認証',
    'features.foundation': '基礎スキル',
    'features.introduction': '業界紹介',
    'features.guidance': 'キャリアガイダンス',
    'features.support': '24時間サポート',
    
    // Course Detail Page
    'courseDetail.overview': '概要',
    'courseDetail.programmeModules': 'プログラムモジュール',
    'courseDetail.iataModules': 'IATAモジュール',
    'courseDetail.communicationSkills': 'コミュニケーションスキル',
    'courseDetail.styleAndImage': 'スタイルとイメージ',
    'courseDetail.aircraftSafety': '航空機安全',
    'courseDetail.harvardModules': 'ハーバード管理モジュール',
    'courseDetail.basicModules': '基本訓練モジュール',
    'courseDetail.harvardDescription': 'リーダーシップ・マネジメントディプロマを取得するには、適格なIATAコースと10のHMM©モジュールの両方を成功裏に完了する必要があります。',
    'courseDetail.entryRequirements': '入学要件',
    'courseDetail.academicRequirements': '学術要件',
    'courseDetail.physicalRequirements': '身体要件',
    'courseDetail.careerOpportunities': 'キャリア機会',
    'courseDetail.perks': 'キャビンクルーの特典',
    'courseDetail.quickInfo': 'クイック情報',
    'courseDetail.contactInfo': '連絡先情報',
    'courseDetail.readyToStart': '旅を始める準備はできましたか？',
    'courseDetail.joinNextIntake': '次の入学と一緒に航空キャリアを今日から始めましょう。',
    'courseDetail.applyNow': '今すぐ申し込む',
    'courseDetail.backToCourses': 'コースに戻る',
    'courseDetail.courseNotFound': 'コースが見つかりません',
    'courseDetail.iataCertified': 'IATA認定プログラム',
    'courseDetail.duration': '期間',
    'courseDetail.study': '学習',
    'courseDetail.intake': '入学',
    'courseDetail.studyWeek': '週3日',
    'courseDetail.intakeMonths': '1月、4月、6月、8月、12月',
    'courseDetail.basedOnAirline': '*航空会社による',
    
    // Course Content - Advanced
    'courses.advanced.subtitle': 'リーダーシップ・マネジメントプログラム',
    'courses.advanced.overview': '世界クラスのリーダーシップ・マネジメントディプロマ。\n\nこのトレーニングプログラムは、IATAの信頼できる航空会社顧客サービスコースまたは航空会社キャビンクルーコースをハーバード・マネジメンター(HMM)©と組み合わせています。これは、ハーバード・ビジネス・スクールの教員、グローバルビジネスリーダー、リーダーシップ開発分野の実践者によって提供される最先端のメディア豊富なトレーニングプラットフォームです。',
    'courses.advanced.modules.iata.1': '今日の航空業界',
    'courses.advanced.modules.iata.2': 'より良い顧客サービス基準',
    'courses.advanced.modules.iata.3': '顧客サービスの新トレンド',
    'courses.advanced.modules.iata.4': '顧客認識',
    'courses.advanced.modules.iata.5': '顧客接触技術',
    'courses.advanced.modules.iata.6': '社会的スタイルと戦術',
    'courses.advanced.modules.iata.7': '苦情処理',
    'courses.advanced.modules.iata.8': 'ストレスとプレッシャーの管理',
    'courses.advanced.modules.communication.1': '英語コミュニケーション',
    'courses.advanced.modules.communication.2': '公衆演説',
    'courses.advanced.modules.communication.3': 'プレゼンテーションスキル',
    'courses.advanced.modules.style.1': 'エチケットと身だしなみ',
    'courses.advanced.modules.style.2': 'スキンケアと衛生',
    'courses.advanced.modules.style.3': 'プロフェッショナルメイクとヘアメイクオーバー',
    'courses.advanced.modules.style.4': 'キャビンクルーの健康的な生活/ライフスタイル',
    
    // 航空機安全モジュール
    'courses.advanced.modules.safety.1': '航空機緊急手順',
    'courses.advanced.modules.safety.2': '火災安全と予防',
    'courses.advanced.modules.safety.3': '避難プロトコル',
    'courses.advanced.modules.safety.4': '医療緊急対応',
    'courses.advanced.modules.safety.5': 'セキュリティ意識訓練',
    'courses.advanced.modules.safety.6': '天候関連安全',
    
    'courses.advanced.modules.harvard.1': 'コーチング',
    'courses.advanced.modules.harvard.2': '顧客フォーカス',
    'courses.advanced.modules.harvard.3': '意思決定',
    'courses.advanced.modules.harvard.4': '職場での倫理',
    'courses.advanced.modules.harvard.5': '目標設定',
    'courses.advanced.modules.harvard.6': 'イノベーションと創造性',
    'courses.advanced.modules.harvard.7': '人をリードする',
    'courses.advanced.modules.harvard.8': '戦略的思考',
    'courses.advanced.modules.harvard.9': 'ストレス管理',
    'courses.advanced.modules.harvard.10': '時間管理',
    
    // Course Content - English
    'courses.english.subtitle': 'ICAOレベル4+認証プログラム',
    'courses.english.overview': 'IATA航空会社顧客サービスコースでキャリアの志を高めましょう。このコースは、ダイナミックな航空世界で成功するための準備をするように設計されています。このプログラムは、卓越した顧客サービスを提供し、忘れられない乗客体験を作り出すために必要な基本的な知識、スキル、態度を提供します。',
    
    // Course Content - Basic
    'courses.basic.subtitle': '基礎プログラム',
    'courses.basic.overview': '航空キャリアの完璧な出発点。この基礎プログラムは、初心者向けの基本的な安全手順、顧客サービス基礎、航空規制をカバーしています。',
    'courses.basic.modules.basic.1': '基本的な安全手順',
    'courses.basic.modules.basic.2': '顧客サービス基礎',
    'courses.basic.modules.basic.3': '航空規制',
    'courses.basic.modules.basic.4': '健康と衛生',
    'courses.basic.modules.basic.5': 'チームワークスキル',
    'courses.basic.modules.basic.6': 'プロフェッショナルな身だしなみ',
    'courses.basic.modules.basic.7': '緊急手順',
    'courses.basic.modules.basic.8': 'コミュニケーション基礎',
    
    // Entry Requirements
    'requirements.academic.1': '高校卒業証明書',
    'requirements.academic.2': '試験/予測結果',
    'requirements.physical.1': '157cm（女性）',
    'requirements.physical.2': '165cm（男性）',
    
    // Career Opportunities
    'career.1': '世界中の国際航空会社',
    'career.2': '航空運航',
    'career.3': 'パイロット候補生',
    'career.4': 'プライベートジェット',
    'career.5': '世界中の空港',
    'career.6': 'ホスピタリティ専門家',
    'career.7': '観光専門家',
    'career.8': '広報専門家',
    'career.9': '顧客サービスエグゼクティブ',
    'career.10': '航空専門トレーナー',
    'career.11': 'パフォーマンス管理',
    'career.12': '航空会社経営',
    'career.13': '採用専門家',
    
    // Perks
    'perks.1': '給与 – RM6000からRM12000*',
    'perks.2': '免税雇用パッケージ',
    'perks.3': '国際医療保険と生命保険',
    'perks.4': '本人と直系家族専用旅行特典*',
    'perks.5': '割引航空券',
    'perks.6': '最大550 USDのウェルカムボーナス*',
    'perks.7': '年間ボーナス*',
    'perks.8': '競争力のある退職特典',
    'perks.9': 'ファストトラック昇進と優れたキャリア機会',
    'perks.10': '家具付き宿泊施設と無料光熱費*',
    'perks.11': '無料通勤交通*',
    'perks.12': '年間最大30日の有給休暇*',
    'perks.13': '高級宿泊ホテル',
    
    // Contact
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '今日から航空の旅を始めましょう',
    'contact.address': '住所',
    'contact.phone': '電話',
    'contact.email': 'メール',
    'contact.hours': '営業時間',
    'contact.hours.weekdays': '月-金: 午前9:00 - 午後6:00',
    'contact.hours.saturday': '土: 午前9:00 - 午後2:00',
    'contact.form.title': 'メッセージを送信',
    'contact.form.name': 'フルネーム',
    'contact.form.email': 'メールアドレス',
    'contact.form.phone': '電話番号',
    'contact.form.message': 'メッセージ',
    'contact.form.submit': 'メッセージ送信',
    'contact.form.submitting': '送信中...',
    'contact.form.success': 'メッセージが正常に送信されました！24時間以内にご返信いたします。',
    'contact.form.error': 'メッセージの送信に失敗しました。後でもう一度お試しください。',
    'contact.form.name.placeholder': 'お名前',
    'contact.form.email.placeholder': 'your.email@example.com',
    'contact.form.phone.placeholder': '+60 12 345 6789',
    'contact.form.message.placeholder': 'キャビンクルー訓練プログラムへのご興味をお聞かせください...',
    'contact.form.course.label': '興味のあるコース',
    'contact.form.course.placeholder': 'コースを選択',
    'contact.form.course.advanced': '上級キャビンクルーディプロマ (1年)',
    'contact.form.course.english': '英語能力向上コース (6ヶ月)',
    'contact.form.course.basic': '基本キャビンクルー訓練 (6ヶ月)',
    'contact.form.attachments': '添付ファイル',
    'contact.form.attachments.optional': 'オプション',
    'contact.form.attachments.hint': '卒業証明書、身分証明書などをアップロードしてください。対応形式：PDF、JPG、PNG、DOC、DOCX',
    'contact.form.attachments.uploaded': 'アップロード済みファイル',
    'contact.form.attachments.remove': '削除',

    // Validation
    'validation.emailDotCom': 'メールアドレスは .com で終わる必要があります',
    'validation.messageRequired': 'メッセージは必須です',
    
    // Contact Section Headers
    'contact.getInTouch': 'お問い合わせ',
    'contact.contactInformation': '連絡先情報',
    
    // Header
    'header.contactUs': 'お問い合わせ',
    'header.selectLanguage': '言語選択',
    
    // Team Members
    'team.title': '私たちのチームメンバー',
    'team.subtitle': 'Valentia Cabin Crew Academyの情熱的な専門家たちをご紹介します。私たちの経験豊富なチームは、航空専門家の未来を形作ることに専念しています。',
    'team.ceo.title': '創設者',
    'team.ceo.description': '航空訓練とビジネス開発に豊富な経験を持つビジョナリーリーダー。キャビンクルー教育の卓越性と革新にコミット。',
    'team.ceo.experience': '航空業界15年以上の経験',
    'team.ceo.expertise': '戦略的リーダーシップ、ビジネス開発、航空規制',
      'team.instructor1.title': '航空訓練専門家',
  'team.instructor1.description': '国際航空会社での経験を持つ経験豊富なキャビンクループロフェッショナル。安全手順と顧客サービス卓越性の専門家。',
  'team.instructor1.experience': 'キャビンクルー12年以上の経験',
  'team.instructor1.expertise': '安全手順、顧客サービス、緊急プロトコル',
  'team.instructor2.title': '英語言語専門家',
  'team.instructor2.description': '航空用語とICAO基準に専門性を持つ認定英語言語講師。学生がICAOレベル4+認証を取得できるよう支援する専門家。',
  'team.instructor2.experience': '英語言語訓練10年以上の経験',
  'team.instructor2.expertise': '航空英語、ICAO基準、発音訓練、コミュニケーション技術',
    'team.experience': '経験',
    'team.expertise': '専門分野',
    'team.contact': '連絡',
    'team.cta.title': '航空の旅を始める準備はできましたか？',
    'team.cta.description': '私たちの専門家チームに参加し、キャビンクルーキャリアへの第一歩を踏み出しましょう。今日私たちに連絡して、訓練プログラムについて詳しく学んでください。',
    'team.cta.button': '始めましょう',
    
    // Course Levels
    'courseLevel.advanced': '上級',
    'courseLevel.englishPlus': '英語プラス',
    'courseLevel.beginner': '初級',
    
    // Course Duration
    'courseDuration.1Year': '1年間',
    'courseDuration.6Months': '6ヶ月',
    
    // Footer
    'footer.rights': 'すべての権利を保有。',
    'footer.description': 'マレーシア最高のキャビンクルー訓練アカデミーで、航空教育と専門開発の卓越性に専念しています。',
    'footer.quickLinks': 'クイックリンク',
    'footer.ourCourses': '私たちのコース',
    'footer.contactInfo': '連絡先情報',
    'footer.admissions': '入学',
    'footer.advancedTraining': '上級キャビンクルー訓練',
    'footer.basicTraining': '基本キャビンクルー訓練',
    'footer.englishProficiency': '英語能力向上',
    'footer.privacyPolicy': 'プライバシーポリシー',
    'footer.termsOfService': '利用規約',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Initialize language from URL parameter on component mount
  React.useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const langParam = urlParams.get('lang');
    if (langParam && ['en', 'zh', 'ko', 'ja'].includes(langParam)) {
      setLanguage(langParam as Language);
    }
  }, []);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};